/**
 * ============================================================================
 * MOCK DATA
 * ============================================================================
 * 
 * This file contains all plain data arrays/objects for the application.
 * All business logic is in mockServices.ts
 * 
 * ============================================================================
 */

import type {
  User,
  TimeEntry,
  LeaveRequest,
  Task,
  Employee,
  OffboardingWorkflow,
  CandidateLegacy,
  JobPosting,
  PerformanceReview,
  DashboardStats,
  LifecycleTimelineEvent,
  OnboardingWorkflow,
} from './mockServices';

// ============================================================================
// MOCK DATA - Organized by Domain
// ============================================================================

// ----------------------------------------------------------------------------
// Domain: Users & Authentication
// ----------------------------------------------------------------------------

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'john.doe@company.com',
    full_name: 'John Doe',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=12',
    department: 'Engineering',
    job_title: 'Senior Software Engineer',
    employee_id: 'EMP-001',
    hire_date: '2022-03-15',
    manager_id: 'user-10',
    phone: '+1-555-0101',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-2',
    email: 'sarah.johnson@company.com',
    full_name: 'Sarah Johnson',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=5',
    department: 'Marketing',
    job_title: 'Marketing Specialist',
    employee_id: 'EMP-002',
    hire_date: '2021-07-20',
    manager_id: 'user-11',
    phone: '+1-555-0102',
    location: 'New York, NY',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-3',
    email: 'michael.chen@company.com',
    full_name: 'Michael Chen',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=8',
    department: 'Engineering',
    job_title: 'Frontend Developer',
    employee_id: 'EMP-003',
    hire_date: '2024-12-01',
    manager_id: 'user-10',
    phone: '+1-555-0103',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'onboarding',
  },
  {
    id: 'user-4',
    email: 'emily.rodriguez@company.com',
    full_name: 'Emily Rodriguez',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=9',
    department: 'Sales',
    job_title: 'Sales Executive',
    employee_id: 'EMP-004',
    hire_date: '2022-09-05',
    manager_id: 'user-12',
    phone: '+1-555-0104',
    location: 'Austin, TX',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-5',
    email: 'david.kim@company.com',
    full_name: 'David Kim',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=13',
    department: 'HR',
    job_title: 'HR Coordinator',
    employee_id: 'EMP-005',
    hire_date: '2021-11-12',
    manager_id: 'user-20',
    phone: '+1-555-0105',
    location: 'Seattle, WA',
    status: 'active',
    lifecycle_state: 'notice',
    notice_period_end: '2024-12-30',
    exit_date: '2024-12-31',
  },
  {
    id: 'user-10',
    email: 'robert.manager@company.com',
    full_name: 'Robert Martinez',
    role: 'manager',
    avatar_url: 'https://i.pravatar.cc/150?img=33',
    department: 'Engineering',
    job_title: 'Engineering Manager',
    employee_id: 'MGR-001',
    hire_date: '2019-04-10',
    phone: '+1-555-0201',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-11',
    email: 'jessica.manager@company.com',
    full_name: 'Jessica Williams',
    role: 'manager',
    avatar_url: 'https://i.pravatar.cc/150?img=44',
    department: 'Marketing',
    job_title: 'Marketing Manager',
    employee_id: 'MGR-002',
    hire_date: '2020-02-14',
    phone: '+1-555-0202',
    location: 'New York, NY',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-12',
    email: 'thomas.manager@company.com',
    full_name: 'Thomas Anderson',
    role: 'manager',
    avatar_url: 'https://i.pravatar.cc/150?img=52',
    department: 'Sales',
    job_title: 'Sales Manager',
    employee_id: 'MGR-003',
    hire_date: '2018-08-22',
    phone: '+1-555-0203',
    location: 'Austin, TX',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-20',
    email: 'amanda.hr@company.com',
    full_name: 'Amanda Cooper',
    role: 'hr',
    avatar_url: 'https://i.pravatar.cc/150?img=45',
    department: 'HR',
    job_title: 'HR Director',
    employee_id: 'HR-001',
    hire_date: '2017-05-30',
    phone: '+1-555-0301',
    location: 'Seattle, WA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-30',
    email: 'richard.exec@company.com',
    full_name: 'Richard Thompson',
    role: 'executive',
    avatar_url: 'https://i.pravatar.cc/150?img=66',
    department: 'Executive',
    job_title: 'Chief Executive Officer',
    employee_id: 'EXEC-001',
    hire_date: '2015-01-15',
    phone: '+1-555-0401',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-26',
    email: 'james.martinez@company.com',
    full_name: 'James Martinez',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=15',
    department: 'Engineering',
    job_title: 'Backend Developer',
    employee_id: 'EMP-026',
    hire_date: '2024-12-15',
    manager_id: 'user-10',
    phone: '+1-555-0126',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'onboarding',
  },
  {
    id: 'user-27',
    email: 'rachel.adams@company.com',
    full_name: 'Rachel Adams',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=16',
    department: 'Finance',
    job_title: 'Senior Accountant',
    employee_id: 'EMP-027',
    hire_date: '2018-03-20',
    manager_id: 'user-20',
    phone: '+1-555-0127',
    location: 'Seattle, WA',
    status: 'active',
    lifecycle_state: 'notice',
    notice_period_end: '2025-01-15',
    exit_date: '2025-01-15',
  },
  {
    id: 'user-6',
    email: 'lisa.anderson@company.com',
    full_name: 'Lisa Anderson',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=10',
    department: 'Engineering',
    job_title: 'Backend Developer',
    employee_id: 'EMP-006',
    hire_date: '2021-06-22',
    manager_id: 'user-10',
    phone: '+1-555-0106',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-7',
    email: 'james.wilson@company.com',
    full_name: 'James Wilson',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=15',
    department: 'Engineering',
    job_title: 'QA Engineer',
    employee_id: 'EMP-007',
    hire_date: '2023-04-18',
    manager_id: 'user-10',
    phone: '+1-555-0107',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-8',
    email: 'emma.davis@company.com',
    full_name: 'Emma Davis',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=25',
    department: 'Engineering',
    job_title: 'DevOps Engineer',
    employee_id: 'EMP-008',
    hire_date: '2022-08-30',
    manager_id: 'user-10',
    phone: '+1-555-0108',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-9',
    email: 'olivia.brown@company.com',
    full_name: 'Olivia Brown',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=20',
    department: 'Marketing',
    job_title: 'Content Marketing Specialist',
    employee_id: 'EMP-009',
    hire_date: '2023-02-14',
    manager_id: 'user-11',
    phone: '+1-555-0109',
    location: 'New York, NY',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-13',
    email: 'alex.taylor@company.com',
    full_name: 'Alex Taylor',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=18',
    department: 'Sales',
    job_title: 'Account Executive',
    employee_id: 'EMP-013',
    hire_date: '2022-11-08',
    manager_id: 'user-12',
    phone: '+1-555-0113',
    location: 'Austin, TX',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-14',
    email: 'sophia.mitchell@company.com',
    full_name: 'Sophia Mitchell',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=47',
    department: 'Engineering',
    job_title: 'Full Stack Developer',
    employee_id: 'EMP-014',
    hire_date: '2024-01-15',
    phone: '+1-555-0114',
    location: 'San Francisco, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-15',
    email: 'ryan.thompson@company.com',
    full_name: 'Ryan Thompson',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=51',
    department: 'Marketing',
    job_title: 'Digital Marketing Specialist',
    employee_id: 'EMP-015',
    hire_date: '2024-02-20',
    phone: '+1-555-0115',
    location: 'New York, NY',
    status: 'active',
    lifecycle_state: 'active',
  },
  {
    id: 'user-16',
    email: 'natalie.white@company.com',
    full_name: 'Natalie White',
    role: 'employee',
    avatar_url: 'https://i.pravatar.cc/150?img=32',
    department: 'Design',
    job_title: 'UI/UX Designer',
    employee_id: 'EMP-016',
    hire_date: '2024-03-10',
    phone: '+1-555-0116',
    location: 'Los Angeles, CA',
    status: 'active',
    lifecycle_state: 'active',
  },
];

// ----------------------------------------------------------------------------
// Domain: Time & Attendance
// ----------------------------------------------------------------------------

export const mockTimeEntries: TimeEntry[] = [
  {
    id: 'time-1',
    employee_id: 'user-1',
    date: '2024-12-13',
    clock_in: '09:00:00',
    clock_out: '17:30:00',
    break_start: '12:00:00',
    break_end: '13:00:00',
    total_hours: 7.5,
    status: 'clocked_out',
  },
  {
    id: 'time-2',
    employee_id: 'user-1',
    date: '2024-12-12',
    clock_in: '08:45:00',
    clock_out: '17:15:00',
    break_start: '12:00:00',
    break_end: '13:00:00',
    total_hours: 7.5,
    status: 'clocked_out',
  },
  {
    id: 'time-3',
    employee_id: 'user-1',
    date: '2024-12-11',
    clock_in: '09:10:00',
    clock_out: '18:00:00',
    break_start: '12:30:00',
    break_end: '13:30:00',
    total_hours: 7.83,
    status: 'clocked_out',
  },
  {
    id: 'time-4',
    employee_id: 'user-1',
    date: '2024-12-10',
    clock_in: '08:55:00',
    clock_out: '17:25:00',
    break_start: '12:00:00',
    break_end: '13:00:00',
    total_hours: 7.5,
    status: 'clocked_out',
  },
  {
    id: 'time-5',
    employee_id: 'user-1',
    date: '2024-12-09',
    clock_in: '09:00:00',
    clock_out: '17:30:00',
    break_start: '12:00:00',
    break_end: '13:00:00',
    total_hours: 7.5,
    status: 'clocked_out',
  },
];

// ----------------------------------------------------------------------------
// Domain: Leave Management
// ----------------------------------------------------------------------------

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    employee_id: 'user-1',
    employee_name: 'John Doe',
    leave_type: 'vacation',
    start_date: '2024-12-23',
    end_date: '2024-12-27',
    days_requested: 5,
    status: 'approved',
    reason: 'Holiday vacation with family',
    approver_id: 'user-20',
    approver_name: 'Amanda Cooper',
    submitted_date: '2024-11-15',
    approved_date: '2024-11-16',
  },
  {
    id: 'leave-2',
    employee_id: 'user-1',
    employee_name: 'John Doe',
    leave_type: 'sick',
    start_date: '2024-11-20',
    end_date: '2024-11-21',
    days_requested: 2,
    status: 'approved',
    reason: 'Medical appointment',
    approver_id: 'user-20',
    approver_name: 'Amanda Cooper',
    submitted_date: '2024-11-18',
    approved_date: '2024-11-18',
  },
  {
    id: 'leave-3',
    employee_id: 'user-1',
    employee_name: 'John Doe',
    leave_type: 'personal',
    start_date: '2025-01-10',
    end_date: '2025-01-10',
    days_requested: 1,
    status: 'pending_manager_approval',
    reason: 'Personal matter',
    submitted_date: '2024-12-10',
  },
  {
    id: 'leave-4',
    employee_id: 'user-3',
    employee_name: 'Michael Chen',
    leave_type: 'vacation',
    start_date: '2025-02-15',
    end_date: '2025-02-20',
    days_requested: 5,
    status: 'pending_hr_approval',
    reason: 'Family vacation',
    approver_id: 'user-10',
    approver_name: 'Robert Martinez',
    submitted_date: '2024-12-01',
  },
  {
    id: 'leave-5',
    employee_id: 'user-2',
    employee_name: 'Sarah Johnson',
    leave_type: 'vacation',
    start_date: '2025-03-01',
    end_date: '2025-03-05',
    days_requested: 4,
    status: 'pending_manager_approval',
    reason: 'Spring break',
    submitted_date: '2024-12-05',
  },
  {
    id: 'leave-6',
    employee_id: 'user-3',
    employee_name: 'Michael Chen',
    leave_type: 'personal',
    start_date: '2025-01-20',
    end_date: '2025-01-22',
    days_requested: 3,
    status: 'pending_manager_approval',
    reason: 'Family event',
    submitted_date: '2024-12-12',
  },
  {
    id: 'leave-7',
    employee_id: 'user-6',
    employee_name: 'Lisa Anderson',
    leave_type: 'vacation',
    start_date: '2025-02-10',
    end_date: '2025-02-14',
    days_requested: 5,
    status: 'pending_manager_approval',
    reason: 'Winter vacation',
    submitted_date: '2024-12-08',
  },
  {
    id: 'leave-8',
    employee_id: 'user-7',
    employee_name: 'James Wilson',
    leave_type: 'sick',
    start_date: '2025-01-05',
    end_date: '2025-01-06',
    days_requested: 2,
    status: 'pending_manager_approval',
    reason: 'Medical appointment',
    submitted_date: '2024-12-11',
  },
  // Manager Leave Requests (go directly to HR)
  {
    id: 'leave-mgr-1',
    employee_id: 'user-10',
    employee_name: 'Robert Martinez',
    leave_type: 'vacation',
    start_date: '2025-02-01',
    end_date: '2025-02-07',
    days_requested: 5,
    status: 'pending_hr_approval',
    reason: 'Family vacation to Hawaii',
    submitted_date: '2024-12-15',
  },
  {
    id: 'leave-mgr-2',
    employee_id: 'user-10',
    employee_name: 'Robert Martinez',
    leave_type: 'personal',
    start_date: '2025-01-15',
    end_date: '2025-01-15',
    days_requested: 1,
    status: 'approved',
    reason: 'Personal appointment',
    approver_id: 'user-20',
    approver_name: 'Amanda Cooper',
    submitted_date: '2024-12-01',
    approved_date: '2024-12-02',
  },
  {
    id: 'leave-mgr-3',
    employee_id: 'user-11',
    employee_name: 'Jessica Williams',
    leave_type: 'vacation',
    start_date: '2025-03-10',
    end_date: '2025-03-14',
    days_requested: 4,
    status: 'pending_hr_approval',
    reason: 'Spring break with family',
    submitted_date: '2024-12-18',
  },
  {
    id: 'leave-mgr-4',
    employee_id: 'user-11',
    employee_name: 'Jessica Williams',
    leave_type: 'sick',
    start_date: '2024-12-20',
    end_date: '2024-12-20',
    days_requested: 1,
    status: 'approved',
    reason: 'Medical checkup',
    approver_id: 'user-20',
    approver_name: 'Amanda Cooper',
    submitted_date: '2024-12-18',
    approved_date: '2024-12-19',
  },
  {
    id: 'leave-mgr-5',
    employee_id: 'user-12',
    employee_name: 'Thomas Anderson',
    leave_type: 'vacation',
    start_date: '2025-04-01',
    end_date: '2025-04-10',
    days_requested: 8,
    status: 'pending_hr_approval',
    reason: 'Extended vacation for anniversary',
    submitted_date: '2024-12-20',
  },
  {
    id: 'leave-mgr-6',
    employee_id: 'user-12',
    employee_name: 'Thomas Anderson',
    leave_type: 'personal',
    start_date: '2025-01-25',
    end_date: '2025-01-25',
    days_requested: 1,
    status: 'pending_hr_approval',
    reason: 'Personal matter',
    submitted_date: '2024-12-22',
  },
];

// Leave Types Configuration
export const mockLeaveTypes = [
  { id: 'leave-type-1', name: 'Annual Leave / Vacation', code: 'ANNUAL', days_per_year: 20, requires_approval: true, notice_days: 7, paid: true, description: 'Annual paid vacation days' },
  { id: 'leave-type-2', name: 'Sick Leave', code: 'SICK', days_per_year: 10, requires_approval: false, notice_days: 0, paid: true, description: 'Paid sick leave' },
  { id: 'leave-type-3', name: 'Casual / Personal Leave', code: 'PERSONAL', days_per_year: 8, requires_approval: true, notice_days: 3, paid: true, description: 'Casual or personal leave days' }
];

// Leave Balances per User
export const mockLeaveBalances = [
  // Employee balances (user-1)
  { id: 'balance-1', user_id: 'user-1', leave_type_id: 'leave-type-1', total_days: 20, used_days: 8, remaining_days: 12, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-2', user_id: 'user-1', leave_type_id: 'leave-type-2', total_days: 10, used_days: 2, remaining_days: 8, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-3', user_id: 'user-1', leave_type_id: 'leave-type-3', total_days: 8, used_days: 1, remaining_days: 7, year: 2025, updated_at: new Date().toISOString() },
  // Manager balances (user-10 - Robert Martinez)
  { id: 'balance-mgr-1', user_id: 'user-10', leave_type_id: 'leave-type-1', total_days: 20, used_days: 1, remaining_days: 19, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-mgr-2', user_id: 'user-10', leave_type_id: 'leave-type-2', total_days: 10, used_days: 0, remaining_days: 10, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-mgr-3', user_id: 'user-10', leave_type_id: 'leave-type-3', total_days: 8, used_days: 0, remaining_days: 8, year: 2025, updated_at: new Date().toISOString() },
  // Manager balances (user-11 - Jessica Williams)
  { id: 'balance-mgr-4', user_id: 'user-11', leave_type_id: 'leave-type-1', total_days: 20, used_days: 0, remaining_days: 20, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-mgr-5', user_id: 'user-11', leave_type_id: 'leave-type-2', total_days: 10, used_days: 1, remaining_days: 9, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-mgr-6', user_id: 'user-11', leave_type_id: 'leave-type-3', total_days: 8, used_days: 0, remaining_days: 8, year: 2025, updated_at: new Date().toISOString() },
  // Manager balances (user-12 - Thomas Anderson)
  { id: 'balance-mgr-7', user_id: 'user-12', leave_type_id: 'leave-type-1', total_days: 20, used_days: 0, remaining_days: 20, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-mgr-8', user_id: 'user-12', leave_type_id: 'leave-type-2', total_days: 10, used_days: 0, remaining_days: 10, year: 2025, updated_at: new Date().toISOString() },
  { id: 'balance-mgr-9', user_id: 'user-12', leave_type_id: 'leave-type-3', total_days: 8, used_days: 0, remaining_days: 8, year: 2025, updated_at: new Date().toISOString() }
];

// ----------------------------------------------------------------------------
// Domain: Tasks & Assignments
// ----------------------------------------------------------------------------

export const mockEmployeeTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Implement User Authentication Module',
    description: 'Develop secure authentication system with JWT tokens, password hashing, and session management. Include multi-factor authentication support.',
    assigned_to_id: 'user-1',
    assigned_to_name: 'John Doe',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    category: 'E-Commerce Platform',
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-2',
    title: 'Code Review: Payment Integration PR #456',
    description: 'Review pull request for Stripe payment gateway integration. Check security best practices, error handling, and test coverage.',
    assigned_to_id: 'user-1',
    assigned_to_name: 'John Doe',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date().toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'urgent',
    status: 'under_review',
    category: 'E-Commerce Platform',
    created_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-3',
    title: 'Optimize Database Query Performance',
    description: 'Analyze and optimize slow-running queries in the user dashboard. Target queries taking more than 500ms. Add proper indexing where needed.',
    assigned_to_id: 'user-1',
    assigned_to_name: 'John Doe',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'pending',
    category: 'Performance Optimization',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-4',
    title: 'Complete Security Training Module',
    description: 'Complete mandatory annual security awareness training covering phishing, data protection, and secure coding practices.',
    assigned_to_id: 'user-1',
    assigned_to_name: 'John Doe',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'completed',
    category: 'Training & Development',
    created_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-5',
    title: 'API Documentation Update',
    description: 'Update REST API documentation for v2 endpoints. Include request/response examples, error codes, and authentication requirements.',
    assigned_to_id: 'user-1',
    assigned_to_name: 'John Doe',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'low',
    status: 'review_completed',
    category: 'Documentation',
    created_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    performance_score: 9.0,
  },
  {
    id: 'task-6',
    title: 'Create Q1 Marketing Campaign Strategy',
    description: 'Develop comprehensive marketing strategy for Q1 product launch. Include social media, email marketing, and content marketing plans.',
    assigned_to_id: 'user-2',
    assigned_to_name: 'Sarah Johnson',
    assigned_by_id: 'user-11',
    assigned_by_name: 'Jessica Williams',
    due_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    category: 'Product Launch Campaign',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-7',
    title: 'Design Social Media Content Calendar',
    description: 'Create monthly social media content calendar for Instagram, LinkedIn, and Twitter. Include post themes, hashtags, and engagement strategies.',
    assigned_to_id: 'user-2',
    assigned_to_name: 'Sarah Johnson',
    assigned_by_id: 'user-11',
    assigned_by_name: 'Jessica Williams',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'completed',
    category: 'Social Media Marketing',
    created_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-8',
    title: 'Analyze Competitor Marketing Strategies',
    description: 'Research and analyze top 5 competitors\' marketing approaches. Document findings in presentation format with recommendations.',
    assigned_to_id: 'user-2',
    assigned_to_name: 'Sarah Johnson',
    assigned_by_id: 'user-11',
    assigned_by_name: 'Jessica Williams',
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'low',
    status: 'review_completed',
    category: 'Market Research',
    created_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_completed_date: new Date().toISOString().split('T')[0],
    performance_score: 8.5,
  },
  {
    id: 'task-9',
    title: 'Build Responsive Dashboard UI',
    description: 'Create responsive dashboard interface using React and Tailwind CSS. Ensure mobile-first design with breakpoints for tablet and desktop.',
    assigned_to_id: 'user-3',
    assigned_to_name: 'Michael Chen',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    category: 'Customer Portal',
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-10',
    title: 'Fix Mobile Navigation Menu Bug',
    description: 'Resolve issue where mobile navigation menu doesn\'t close after selecting an item. Test on iOS and Android devices.',
    assigned_to_id: 'user-3',
    assigned_to_name: 'Michael Chen',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date().toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'urgent',
    status: 'completed',
    category: 'Bug Fixes',
    created_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-11',
    title: 'Implement Dark Mode Theme',
    description: 'Add dark mode toggle functionality to the application. Create theme context and ensure all components support both light and dark themes.',
    assigned_to_id: 'user-3',
    assigned_to_name: 'Michael Chen',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'under_review',
    category: 'UI/UX Enhancement',
    created_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-12',
    title: 'Prepare Client Proposal for TechCorp',
    description: 'Create comprehensive sales proposal for TechCorp enterprise account. Include pricing, features, implementation timeline, and ROI analysis.',
    assigned_to_id: 'user-4',
    assigned_to_name: 'Emily Rodriguez',
    assigned_by_id: 'user-12',
    assigned_by_name: 'Thomas Anderson',
    due_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'urgent',
    status: 'pending',
    category: 'Enterprise Sales',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-13',
    title: 'Follow Up with Q4 Leads',
    description: 'Contact and follow up with 20 qualified leads from Q4. Schedule demos and provide product information packages.',
    assigned_to_id: 'user-4',
    assigned_to_name: 'Emily Rodriguez',
    assigned_by_id: 'user-12',
    assigned_by_name: 'Thomas Anderson',
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'completed',
    category: 'Lead Management',
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-14',
    title: 'Update CRM with Latest Client Interactions',
    description: 'Log all recent client meetings, calls, and email communications in CRM system. Ensure data accuracy and completeness.',
    assigned_to_id: 'user-4',
    assigned_to_name: 'Emily Rodriguez',
    assigned_by_id: 'user-12',
    assigned_by_name: 'Thomas Anderson',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'pending',
    category: 'CRM Management',
    created_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-15',
    title: 'Design RESTful API Architecture',
    description: 'Design and document RESTful API architecture for microservices. Include authentication, rate limiting, and error handling patterns.',
    assigned_to_id: 'user-6',
    assigned_to_name: 'Lisa Anderson',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    category: 'API Development',
    created_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-16',
    title: 'Implement Caching Layer with Redis',
    description: 'Set up Redis caching layer for frequently accessed data. Configure cache invalidation strategies and monitor cache hit rates.',
    assigned_to_id: 'user-6',
    assigned_to_name: 'Lisa Anderson',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'completed',
    category: 'Performance Optimization',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-17',
    title: 'Write Unit Tests for Payment Service',
    description: 'Create comprehensive unit tests for payment processing service. Achieve minimum 90% code coverage with edge case testing.',
    assigned_to_id: 'user-6',
    assigned_to_name: 'Lisa Anderson',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'review_completed',
    category: 'Quality Assurance',
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_completed_date: new Date().toISOString().split('T')[0],
    performance_score: 9.5,
  },
  {
    id: 'task-18',
    title: 'Create Test Plan for User Registration Flow',
    description: 'Develop comprehensive test plan covering functional, integration, and security testing for user registration and email verification process.',
    assigned_to_id: 'user-7',
    assigned_to_name: 'James Wilson',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    category: 'Test Planning',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-19',
    title: 'Execute Regression Test Suite',
    description: 'Run full regression test suite for v2.1 release. Document all test results and report any critical bugs found.',
    assigned_to_id: 'user-7',
    assigned_to_name: 'James Wilson',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'urgent',
    status: 'under_review',
    category: 'Quality Assurance',
    created_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'task-20',
    title: 'Automate E2E Tests with Playwright',
    description: 'Set up Playwright framework and create end-to-end tests for critical user journeys. Integrate with CI/CD pipeline.',
    assigned_to_id: 'user-7',
    assigned_to_name: 'James Wilson',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'review_completed',
    category: 'Test Automation',
    created_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_completed_date: new Date().toISOString().split('T')[0],
    performance_score: 8.0,
  },
  {
    id: 'task-21',
    title: 'Set Up Kubernetes Cluster for Production',
    description: 'Configure Kubernetes cluster on AWS EKS. Set up auto-scaling, load balancing, and monitoring with Prometheus and Grafana.',
    assigned_to_id: 'user-8',
    assigned_to_name: 'Emma Davis',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    category: 'Infrastructure Setup',
    created_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-22',
    title: 'Implement CI/CD Pipeline with GitHub Actions',
    description: 'Create automated CI/CD pipeline for code deployment. Include automated testing, security scanning, and deployment to staging/production.',
    assigned_to_id: 'user-8',
    assigned_to_name: 'Emma Davis',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'completed',
    category: 'DevOps Automation',
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-23',
    title: 'Configure Application Monitoring and Alerts',
    description: 'Set up comprehensive monitoring for application performance, errors, and resource usage. Configure alerting rules for critical metrics.',
    assigned_to_id: 'user-8',
    assigned_to_name: 'Emma Davis',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'pending',
    category: 'Monitoring & Observability',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-24',
    title: 'Write Blog Post: "10 Tips for Remote Team Collaboration"',
    description: 'Create engaging blog post about remote team collaboration best practices. Include case studies and actionable tips. Target 2000+ words.',
    assigned_to_id: 'user-9',
    assigned_to_name: 'Olivia Brown',
    assigned_by_id: 'user-11',
    assigned_by_name: 'Jessica Williams',
    due_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'pending',
    category: 'Content Marketing',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-25',
    title: 'Create Email Newsletter Template',
    description: 'Design responsive email newsletter template for monthly product updates. Ensure compatibility across major email clients.',
    assigned_to_id: 'user-9',
    assigned_to_name: 'Olivia Brown',
    assigned_by_id: 'user-11',
    assigned_by_name: 'Jessica Williams',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'low',
    status: 'review_completed',
    category: 'Email Marketing',
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_completed_date: new Date().toISOString().split('T')[0],
    performance_score: 7.5,
  },
  {
    id: 'task-26',
    title: 'Schedule Product Demo for GlobalTech Inc.',
    description: 'Coordinate with GlobalTech Inc. to schedule product demonstration. Prepare customized demo script based on their business needs.',
    assigned_to_id: 'user-13',
    assigned_to_name: 'Alex Taylor',
    assigned_by_id: 'user-12',
    assigned_by_name: 'Thomas Anderson',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'urgent',
    status: 'pending',
    category: 'Sales Pipeline',
    created_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-27',
    title: 'Prepare Quarterly Sales Report',
    description: 'Compile Q4 sales data including revenue, deals closed, conversion rates, and pipeline analysis. Present findings to management.',
    assigned_to_id: 'user-13',
    assigned_to_name: 'Alex Taylor',
    assigned_by_id: 'user-12',
    assigned_by_name: 'Thomas Anderson',
    due_date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'completed',
    category: 'Sales Reporting',
    created_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-28',
    title: 'Renewal Outreach for Existing Clients',
    description: 'Contact 15 clients with contracts expiring in Q1. Discuss renewal terms and address any concerns or feature requests.',
    assigned_to_id: 'user-13',
    assigned_to_name: 'Alex Taylor',
    assigned_by_id: 'user-12',
    assigned_by_name: 'Thomas Anderson',
    due_date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'under_review',
    category: 'Account Management',
    created_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    review_started_date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'task-29',
    title: 'Onboarding: Complete Development Environment Setup',
    description: 'Set up local development environment including IDE, database, API keys, and access to code repositories. Complete onboarding checklist.',
    assigned_to_id: 'user-26',
    assigned_to_name: 'James Martinez',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    category: 'Onboarding',
    created_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'task-30',
    title: 'Review Codebase Architecture Documentation',
    description: 'Study existing codebase architecture, design patterns, and coding standards. Schedule meeting with team lead for questions.',
    assigned_to_id: 'user-26',
    assigned_to_name: 'James Martinez',
    assigned_by_id: 'user-10',
    assigned_by_name: 'Robert Martinez',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    assigned_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'completed',
    category: 'Onboarding',
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
];

// ----------------------------------------------------------------------------
// Domain: Employee Management (HR)
// ----------------------------------------------------------------------------

export const mockAllEmployees: Employee[] = [
  ...mockUsers.map(user => ({
    id: user.id,
    employee_id: user.employee_id,
    full_name: user.full_name,
    email: user.email,
    phone: user.phone,
    job_title: user.job_title,
    department: user.department,
    manager_id: user.manager_id,
    manager_name: user.manager_id ? mockUsers.find(u => u.id === user.manager_id)?.full_name : undefined,
    hire_date: user.hire_date,
    status: user.status,
    employment_type: 'full_time' as const,
    location: user.location || 'Remote',
    salary: user.role === 'executive' ? 250000 : user.role === 'manager' ? 120000 : 85000,
    avatar_url: user.avatar_url,
    skills: ['JavaScript', 'React', 'TypeScript'],
    certifications: ['AWS Certified', 'Scrum Master'],
  })),
  {
    id: 'user-15',
    employee_id: 'EMP-015',
    full_name: 'Rachel Green',
    email: 'rachel.green@company.com',
    phone: '+1-555-0115',
    job_title: 'Product Designer',
    department: 'Design',
    manager_id: 'user-11',
    manager_name: 'Jessica Williams',
    hire_date: '2023-03-15',
    status: 'active',
    employment_type: 'full_time',
    location: 'Los Angeles, CA',
    salary: 95000,
    avatar_url: 'https://i.pravatar.cc/150?img=47',
    skills: ['Figma', 'UI/UX', 'Prototyping'],
    certifications: ['UX Certification'],
  },
];

// ----------------------------------------------------------------------------
// Domain: Recruitment
// ----------------------------------------------------------------------------

// Note: This is the old mockCandidates from the original mockServices
// The recruitmentService has its own internal mockCandidates
export const mockCandidates: CandidateLegacy[] = [
  {
    id: 'cand-1',
    full_name: 'Jennifer Lee',
    email: 'jennifer.lee@email.com',
    phone: '+1-555-9001',
    position_applied: 'Senior React Developer',
    department: 'Engineering',
    source: 'linkedin',
    status: 'interviewing',
    applied_date: '2024-11-20',
    experience_years: 6,
    expected_salary: 125000,
    interview_stage: 'Technical Round 2',
    notes: 'Strong React and TypeScript skills. Good cultural fit.',
  },
  {
    id: 'cand-2',
    full_name: 'Marcus Johnson',
    email: 'marcus.j@email.com',
    phone: '+1-555-9002',
    position_applied: 'Product Manager',
    department: 'Product',
    source: 'referral',
    status: 'offer',
    applied_date: '2024-11-15',
    experience_years: 8,
    expected_salary: 140000,
    interview_stage: 'Final Round Complete',
    notes: 'Excellent product experience. Ready for offer.',
  },
  {
    id: 'cand-3',
    full_name: 'Olivia Chen',
    email: 'olivia.chen@email.com',
    phone: '+1-555-9003',
    position_applied: 'UX Designer',
    department: 'Design',
    source: 'job_board',
    status: 'screening',
    applied_date: '2024-12-01',
    experience_years: 4,
    expected_salary: 95000,
    interview_stage: 'Phone Screen Scheduled',
  },
  {
    id: 'cand-4',
    full_name: 'Daniel Park',
    email: 'daniel.park@email.com',
    phone: '+1-555-9004',
    position_applied: 'DevOps Engineer',
    department: 'Engineering',
    source: 'direct_application',
    status: 'new',
    applied_date: '2024-12-10',
    experience_years: 5,
    expected_salary: 115000,
  },
];

export const mockJobPostings: JobPosting[] = [
  {
    id: 'job-1',
    title: 'Senior React Developer',
    department: 'Engineering',
    location: 'San Francisco, CA / Remote',
    employment_type: 'full_time',
    experience_level: 'senior',
    salary_range_min: 120000,
    salary_range_max: 160000,
    description: 'We are looking for an experienced React developer to join our frontend team.',
    requirements: [
      '5+ years of React experience',
      'Strong TypeScript skills',
      'Experience with modern build tools',
      'Testing experience (Jest, React Testing Library)',
    ],
    posted_date: '2024-11-10',
    closing_date: '2024-12-31',
    status: 'active',
    applications_count: 24,
  },
  {
    id: 'job-2',
    title: 'Product Manager',
    department: 'Product',
    location: 'New York, NY',
    employment_type: 'full_time',
    experience_level: 'senior',
    salary_range_min: 130000,
    salary_range_max: 170000,
    description: 'Seeking a strategic product manager to lead our core product initiatives.',
    requirements: [
      '7+ years product management experience',
      'B2B SaaS experience',
      'Data-driven decision making',
      'Excellent communication skills',
    ],
    posted_date: '2024-11-05',
    status: 'active',
    applications_count: 18,
  },
  {
    id: 'job-3',
    title: 'UX Designer',
    department: 'Design',
    location: 'Remote',
    employment_type: 'full_time',
    experience_level: 'mid',
    salary_range_min: 85000,
    salary_range_max: 110000,
    description: 'Join our design team to create delightful user experiences.',
    requirements: [
      '3+ years UX design experience',
      'Figma proficiency',
      'User research experience',
      'Portfolio required',
    ],
    posted_date: '2024-11-25',
    status: 'active',
    applications_count: 31,
  },
];

// Performance Reviews (used by hrDashboardStats)
export const mockAllPerformanceReviews: PerformanceReview[] = [
  {
    id: 'review-10',
    employee_id: 'user-2',
    employee_name: 'Sarah Johnson',
    reviewer_id: 'user-11',
    reviewer_name: 'Jessica Williams',
    review_period: 'Q3 2024',
    review_date: '2024-10-18',
    overall_rating: 4.3,
    ratings: {
      quality_of_work: 4,
      productivity: 5,
      communication: 4,
      teamwork: 4,
      leadership: 4,
      innovation: 5,
    },
    strengths: [
      'Creative campaign strategies',
      'Strong analytical skills',
      'Excellent stakeholder management',
    ],
    areas_for_improvement: [
      'Delegation skills',
      'Meeting deadlines',
    ],
    goals_met: 9,
    goals_total: 10,
    comments: 'Sarah has delivered exceptional marketing campaigns this quarter.',
    status: 'completed',
  },
];

// ----------------------------------------------------------------------------
// Domain: Dashboard Statistics
// ----------------------------------------------------------------------------

export const hrDashboardStats: DashboardStats = {
  employees: {
    total: mockAllEmployees.length,
    active: mockAllEmployees.filter(e => e.status === 'active').length,
    on_leave: mockAllEmployees.filter(e => e.status === 'on_leave').length,
    new_this_month: 3,
  },
  attendance: {
    present_today: 42,
    absent_today: 2,
    on_leave_today: 3,
    late_today: 1,
    average_attendance_rate: 96.5,
  },
  leave: {
    pending_requests: mockLeaveRequests.filter(l => 
      l.status === 'pending_manager_approval' || l.status === 'pending_hr_approval'
    ).length,
    approved_this_month: 12,
    total_days_taken: 145,
  },
  performance: {
    average_rating: 4.3,
    reviews_completed: mockAllPerformanceReviews.filter(r => r.status === 'completed').length,
    reviews_pending: 8,
    high_performers: 15,
  },
  recruitment: {
    open_positions: mockJobPostings.filter(j => j.status === 'active').length,
    active_candidates: mockCandidates.length,
    interviews_scheduled: 5,
    offers_pending: mockCandidates.filter(c => c.status === 'offer').length,
  },
};

// ----------------------------------------------------------------------------
// Domain: Employee Lifecycle - Timeline Events
// ----------------------------------------------------------------------------

export const mockLifecycleTimelineEvents: LifecycleTimelineEvent[] = [
  {
    id: 'timeline-1',
    employee_id: 'user-3',
    event_type: 'state_change',
    title: 'Started Onboarding',
    description: 'Employee moved from Hired to Onboarding',
    from_state: 'hired',
    to_state: 'onboarding',
    date: '2024-12-01',
    created_by: 'hr-user-1'
  },
  {
    id: 'timeline-2',
    employee_id: 'user-5',
    event_type: 'state_change',
    title: 'Notice Period Started',
    description: 'Employee submitted resignation',
    from_state: 'active',
    to_state: 'notice',
    date: '2024-12-01',
    created_by: 'hr-user-1'
  }
];

// ----------------------------------------------------------------------------
// Domain: Employee Lifecycle - Onboarding
// ----------------------------------------------------------------------------

export const mockOnboardingWorkflowsDetailed: OnboardingWorkflow[] = [
  {
    id: 'onboard-1',
    employee_id: 'user-3',
    employee_name: 'Michael Chen',
    start_date: '2024-12-01',
    status: 'in_progress' as const,
    progress: 60,
    checklist: [
      {
        id: 'check-1',
        title: 'Offer letter signed',
        description: 'Employment offer letter signed by employee',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-11-28',
        completed_by: 'hr-user-1'
      },
      {
        id: 'check-2',
        title: 'Documents verified',
        description: 'ID, background check, references verified',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-11-30',
        completed_by: 'hr-user-1'
      },
      {
        id: 'check-3',
        title: 'Role & department assigned',
        description: 'Job title and reporting structure confirmed',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-12-01',
        completed_by: 'hr-user-1'
      },
      {
        id: 'check-4',
        title: 'System access granted',
        description: 'Email, tools, and system permissions set up',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'check-5',
        title: 'Initial training assigned',
        description: 'Onboarding training modules assigned',
        assigned_to: 'manager' as const,
        status: 'pending' as const
      }
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Complete HR Paperwork',
        description: 'Fill out all required employment forms',
        assigned_to: 'HR Department',
        due_date: '2024-11-28',
        status: 'completed' as const,
        category: 'documentation' as const
      },
      {
        id: 'task-2',
        title: 'Setup Workstation',
        description: 'Prepare laptop and desk setup',
        assigned_to: 'IT Department',
        due_date: '2024-11-30',
        status: 'completed' as const,
        category: 'equipment' as const
      },
      {
        id: 'task-3',
        title: 'Complete Security Training',
        description: 'Mandatory security awareness training',
        assigned_to: 'Michael Chen',
        due_date: '2024-12-05',
        status: 'in_progress' as const,
        category: 'training' as const
      }
    ]
  },
  {
    id: 'onboard-2',
    employee_id: 'user-26',
    employee_name: 'James Martinez',
    start_date: '2024-12-15',
    status: 'in_progress' as const,
    progress: 40,
    checklist: [
      {
        id: 'check-6',
        title: 'Offer letter signed',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-12-10'
      },
      {
        id: 'check-7',
        title: 'Documents verified',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-12-12'
      },
      {
        id: 'check-8',
        title: 'Role & department assigned',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'check-9',
        title: 'System access granted',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'check-10',
        title: 'Initial training assigned',
        assigned_to: 'manager' as const,
        status: 'pending' as const
      }
    ],
    tasks: []
  }
];

// ----------------------------------------------------------------------------
// Domain: Employee Lifecycle - Offboarding
// ----------------------------------------------------------------------------

export const mockOffboardingWorkflowsDetailed: OffboardingWorkflow[] = [
  {
    id: 'offboard-1',
    employee_id: 'user-5',
    employee_name: 'David Kim',
    termination_date: '2024-12-31',
    last_working_day: '2024-12-30',
    status: 'in_progress' as const,
    reason: 'resignation' as const,
    progress: 50,
    exit_interview_completed: false,
    checklist: [
      {
        id: 'offcheck-1',
        title: 'Resignation acknowledged',
        description: 'Resignation letter received and acknowledged',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-12-01',
        completed_by: 'hr-user-1'
      },
      {
        id: 'offcheck-2',
        title: 'Notice period tracked',
        description: 'Notice period start and end dates confirmed',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-12-01',
        completed_by: 'hr-user-1'
      },
      {
        id: 'offcheck-3',
        title: 'Asset return completed',
        description: 'Laptop, badge, keys returned',
        assigned_to: 'manager' as const,
        status: 'pending' as const
      },
      {
        id: 'offcheck-4',
        title: 'System access revoked',
        description: 'All system access and credentials disabled',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'offcheck-5',
        title: 'Final payroll cleared',
        description: 'Final paycheck and benefits calculated',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'offcheck-6',
        title: 'Exit interview completed',
        description: 'Exit interview conducted and documented',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      }
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Exit Interview',
        description: 'Conduct exit interview with departing employee',
        assigned_to: 'HR Manager',
        due_date: '2024-12-20',
        status: 'pending' as const,
        category: 'exit_interview' as const
      },
      {
        id: 'task-2',
        title: 'Return Equipment',
        description: 'Collect laptop, badges, and other company property',
        assigned_to: 'IT Department',
        due_date: '2024-12-31',
        status: 'pending' as const,
        category: 'equipment' as const
      }
    ]
  },
  {
    id: 'offboard-2',
    employee_id: 'user-27',
    employee_name: 'Rachel Adams',
    termination_date: '2025-01-15',
    last_working_day: '2025-01-15',
    status: 'initiated' as const,
    reason: 'retirement' as const,
    progress: 20,
    exit_interview_completed: false,
    checklist: [
      {
        id: 'offcheck-7',
        title: 'Resignation acknowledged',
        assigned_to: 'hr' as const,
        status: 'completed' as const,
        completed_date: '2024-12-15'
      },
      {
        id: 'offcheck-8',
        title: 'Notice period tracked',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'offcheck-9',
        title: 'Asset return completed',
        assigned_to: 'manager' as const,
        status: 'pending' as const
      },
      {
        id: 'offcheck-10',
        title: 'System access revoked',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'offcheck-11',
        title: 'Final payroll cleared',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      },
      {
        id: 'offcheck-12',
        title: 'Exit interview completed',
        assigned_to: 'hr' as const,
        status: 'pending' as const
      }
    ],
    tasks: []
  }
];

// ----------------------------------------------------------------------------
// Domain: Policies & Compliance
// ----------------------------------------------------------------------------

export const mockPolicies = [
  {
    id: 'policy-1',
    title: 'Remote Work Policy',
    category: 'work_arrangements' as const,
    description: 'Guidelines for remote work arrangements',
    content: 'Full policy content here...',
    version: '1.2',
    effective_date: '2024-01-01',
    review_date: '2025-01-01',
    status: 'active' as const,
    owner: 'HR Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: 'policy-2',
    title: 'Code of Conduct',
    category: 'conduct' as const,
    description: 'Company code of conduct and ethics',
    content: 'Full policy content here...',
    version: '2.0',
    effective_date: '2024-01-01',
    review_date: '2025-01-01',
    status: 'active' as const,
    owner: 'Legal Department',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  }
];

// ----------------------------------------------------------------------------
